### ISSUE TITLE
Error pulling from dvc

### ISSUE THREAD

**Issue by michael-knight** [EdenBD/MultiModalStory-demo#3]
When I run `dvc pull -f` I get the following output:

```
WARNING: No file hash info found for 'backend/unsplash-dataset'. It won't be created.
WARNING: No file hash info found for 'backend/story_generator/downloaded'. It won't be created.
WARNING: No file hash info found for 'backend/outputs'. It won't be created.
3 files failed
ERROR: failed to pull data from the cloud - Checkout failed for following targets:
backend/unsplash-dataset
backend/story_generator/downloaded
backend/outputs
Is your cache up to date?
<https://error.dvc.org/missing-files>
```

**Comment by gonbaum** [comment]
In my case, when i run `dvc pull -f` i get:

`ERROR: failed to pull data from the cloud - config file error: no remote specified. Create a default remote with
    dvc remote add -d <remote name> <remote url>`

**Comment by EdenBD** [comment]
Thank you for the details, as for issue #5 `.dvc/config` was added to solve this issue. 
Please let us know if you have further issues.
