### ISSUE TITLE
fairytailor.org is down?

### ISSUE THREAD

**Issue by sterlinm** [EdenBD/MultiModalStory-demo#4]
It appears that (as of ~8/14/2021 1:00pm EST) [fairytailor.org](https://fairytailor.org) is down. No big deal, just wanted to check it out.

According to [Down For Everyone or Just Me](https://downforeveryoneorjustme.com/fairytailor.org) it's not just me.

<img width="613" alt="Screen Shot 2021-08-14 at 1 13 54 PM" src="https://user-images.githubusercontent.com/1461273/129455136-398e8798-f942-4c48-bc5f-7fac984800cf.png">

**Comment by EdenBD** [comment]
Hello :D Thank you so much for the feedback. 

The platform is available in a new URL: https://fairytailor.vizhub.ai/ 
I'll update it in the readme. Please let us know if you have further comments.
