### ISSUE TITLE
.dvc/config file missing

### ISSUE THREAD

**Issue by timeeehd** [EdenBD/MultiModalStory-demo#5]
After installation, the next step is to pull all the files: Our large data files are stored on IBM's Cloud Object Storage, and to pull data files from that platform you will use a special, read-only .dvc/config file.

But after the following command dvc pull -f

I get the following:
![image](https://user-images.githubusercontent.com/41724518/158054135-21c96e8e-fd90-414f-925a-9987549fd807.png)

Does it mean there is something missing in the repository?

**Comment by EdenBD** [comment]
You're right, thank you for the details.
`.dvc/config` was added to solve this issue. 
Huge thank you @bhoov
