### ISSUE TITLE
Security issue in MultiModalStory-demo

### ISSUE THREAD

**Issue by nadav-legit** [EdenBD/MultiModalStory-demo#6]
Hello,
During a security audit scan we performed on your project, we found a critical security issue. Publicly exposed credentials!
We want to initiate a disclosure process.

Please feel free to reply at [nadav@legitseucrity.com](mailto:nadav@legitseucrity.com)

**Comment by natan-artoh** [comment]
Just found it too :o
Maybe it was supposed to be that way? 
https://github.com/EdenBD/MultiModalStory-demo/tree/master#large-data-management-dvc

**Comment by EdenBD** [comment]
Hi Nadav and Natan, thank you so much for looking at it. 
The config is intentionally public. It provides read-only permissions to allow others to download the trained models, images and stories.
